name:                advent20
version:             0.1.0.0
github:              "jamespjh/advent20"
license:             BSD3
author:              "James Hetherington"
maintainer:          "jamespjh@gmail.com"
copyright:           "2020 James Hetherington"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jamespjh/advent20#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  advent20-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent20

tests:
  advent20-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent20
